development:
  adapter: postgresql
  database: rotpot_development
  pool: 5
  timeout: 5000
  host: localhost

test:
  adapter: postgresql
  database: rotpot_test
  pool: 5
  timeout: 5000
  host: localhost

production:
  adapter: postgresql
  database: rotpot_production
  pool: 5
  timeout: 5000
  host: localhost